# File 1: .github/workflows/environment_variables.yml
name: Environment Variables Example

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello" # Define an environment variable
      TARGET: "GitHub Actions" # Define another environment variable
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Greeting
        run: echo "$GREETING, $TARGET!" # Use environment variables