name: CI Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Hello World
        run: echo "Hello, GitHub Actions!"