name: Production Environment Workflow
on:
  push:
    branches:
      - main

jobs:
  production_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Production Secret
        run: |
          echo "The production environment secret is: ${{ secrets.PRODUCTION_API_KEY }}"
