# File: .github/workflows/schedule.yml
name: Scheduled Trigger Example

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  run-on-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled Run
        run: echo "This workflow runs every day at 12 PM UTC!"
