name: Scheduled Workflow
on:
  schedule:
    # Runs at 12:00 AM UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Scheduled Job
        run: echo "Executing scheduled task..."