name: Scheduled Workflow # Workflow name

on: # Workflow triggers
  schedule: # Automatic trigger based on cron schedule
    - cron: "0 0 * * *" # Runs at 12:00 AM UTC daily
  workflow_dispatch: # Enables manual triggering from GitHub UI

jobs: # Define the job(s) to execute
  build: # Job name
    runs-on: ubuntu-latest # Specify the runner (OS environment)
    steps: # Steps to execute in the job
      - name: Checkout Code # Step 1: Check out repository code
        uses: actions/checkout@v2

      - name: Run Scheduled Job # Step 2: Run the scheduled task
        run: echo "Executing scheduled task..." # Command to execute