name: Secure Secrets Workflow
on: 
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "The secret is: ${{ secrets.MY_SECRET }}"