name: Staging Environment Workflow
on:
  push:
    branches:
      - main

jobs:
  staging_job:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Staging Secret
        run: |
          echo "The staging environment secret is: ${{ secrets.STAGING_API_KEY }}"