# File 3: .github/workflows/step_level_environment_variables.yml
name: Step-Level Environment Variables Example

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Step-Level Environment Variable
        env:
          CUSTOM_GREETING: "Hi"
        run: echo "$CUSTOM_GREETING, GitHub Actions!" # Step-level environment variable

      - name: Print GitHub Branch
        run: echo "Current branch: ${GITHUB_REF#refs/heads/}" # Built-in GitHub environment variable